language: csharp
dist: xenial
dotnet: 3.0.100
mono: none

os:
  - linux

script:
 - cd NetCoreOpenSource
 - dotnet tool install --global FlubuCore.GlobalTool --version 4.2.8
 - flubu Rebuild.Server -apiKey=${Nuget_Api_Key}
