language: csharp
os:
  - linux
sudo: required  
dist: xenial
mono: none
dotnet: 3.0.100

git:
  depth: false

script:
  - export PATH="$PATH:$HOME/.dotnet/tools"
  - dotnet tool install --global FlubuCore.GlobalTool --version 4.2.8
  - cd NetCoreOpenSource
  - flubu Rebuild.Server -apiKey=${Nuget_Api_Key} # {Nuget_Api_Key} environment variable must be added in travis
